apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "redhat-operators-instrumented"
  namespace: "openshift-marketplace"
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  sourceType: grpc
  image: quay.io/ecordell/redhat-operator-index:v4.8-metrics
  displayName: "Red Hat Operators (Instrumented)"
  publisher: "Red Hat"
  priority: -200
  updateStrategy:
    registryPoll:
      interval: 10m